"""add Department

Revision ID: 59768b9bf6bf
Revises: 5eeeb94b5e52
Create Date: 2025-09-19 10:56:15.888651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59768b9bf6bf'
down_revision = '5eeeb94b5e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
